# Site settings
title: amemay.com
description: ame's things and stuff.
keywords: Blog
author: ame
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
robots: none

# Link settings
links:
  show: false
  twitter: #username
  instagram: #username
  facebook: #username
  tumblr: #username

